# Start using docker-compose
FROM tensorflow/tensorflow:2.4.1-gpu

COPY ./requirements.in /app/requirements.in
WORKDIR /app

RUN pip install pip-tools
RUN pip-compile
RUN pip install -r requirements.txt

ENV TF_FORCE_GPU_ALLOW_GROWTH true
ENTRYPOINT ["python", "-m", "src.evaluate"]
